--- #YAML:1.0
name:               Bundle-Woldrich-Term
version:            0.02
abstract:           Terminal related modules and applications
author:
    - Magnus Woldrich <m@japh.se>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    bugtracker:  https://github.com/trapd00r/Bundle-Woldrich-Term/issues
    repository:  https://github.com/trapd00r/Bundle-Woldrich-Term
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
